name: Issue → Branch
on:
  issues:
    types: [opened, reopened]
jobs:
  create:
    runs-on: ubuntu-latest
    steps:
      - uses: tibdex/create-issue-branch@v5
        with:
          branch_suffix: ""
