name: Auto PR on Push
on:
  push:
    branches:
      - "issue/**"

jobs:
  create_pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
<<<<<<< HEAD
        with:
          fetch-depth: 0
      
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: auto PR from ${{ github.ref_name }}"
          title: "Auto PR from ${{ github.ref_name }}"
          body: |
            このPRは自動生成されました。
            
            ## 変更内容
            - 自動生成されたコード
            
            ## レビュー項目
            - [ ] コードの正確性
            - [ ] テストの網羅性
            - [ ] ドキュメントの正確性
          draft: true
          branch: ${{ github.ref_name }}
          base: main
=======

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "chore: auto PR from ${GITHUB_REF_NAME}"
          title: "Auto PR from ${GITHUB_REF_NAME}"
          body: "This pull request was automatically generated."
          draft: true
>>>>>>> 71d6162cc6dd729ffe2e29683176600597ce7151
