name: Issue → Branch
on:
  issues:
    types: [opened, reopened]
jobs:
  create:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Create Issue Branch
        uses: robvanderleek/create-issue-branch@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch_name: 'issue/${issue.number}-${issue.title}'
          mode: replace
          replacementPattern: '[^a-zA-Z0-9_-]'
          replacement: '-'