name: Issue → Branch
on:
  issues:
    types: [opened, reopened]
jobs:
  create:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: tibdex/create-issue-branch@v5
        with:
          branch_suffix: ""